### PR TITLE
Add support for alternate 3D preview engines

### LINKED ISSUE #5: Add support for alternate 3D preview engines
I'm actually in the process of implementing this, but I'm creating this issue mostly so that you're aware that the development is going on.

I'm currently updating the 2.0 branch of this extension to allow for the preview pane to switch between Cesium, Babylon.js, Three.js and Osg.js.  It also adds a configuration option to choose what the default renderer should be, even though it also provides a menu within the preview pane itself to switch on the fly.

### PR DESCRIPTION
**Pull request by HowardWolosky**
## Summary
At its core, this adds the ability to preview glTF models with three different engines:
   * [Cesium](http://cesiumjs.org) (support already existed)
   * [Babylon.js](http://babylonjs.com)
   * [Three.js](http://threejs.org)

>I had issues getting [osg.js](http://osgjs.org) working. This should be revisited at a later date.

Users have the ability to change the current preview engine on the fly via an embedded menu (using [dat.gui](https://github.com/dataarts/dat.gui), as well as being able to set what the default preview engine should be via a new VS Code setting.

The design of this change is a little complicated due to the limitations of VS Code preview windows as well as with the 3D engines themselves.

## Known limitations
* Cesium is the only engine of the three that will preview _live content_ in the tab.  The other engines will preview the _saved_ content of the file open in the tab.
* Cesium doesn't appear to support glTF 2.0 yet while the other engines do.
* Babylon.js appears to be having trouble displaying glTF 1.0 files in VS Code, but is doing fine with 2.0.  It appears related to how it uses Blob URI's internally and needs to be investigated further by the Babylon folks (a bug will be filed).

## Overall design
VS Code preview windows cannot navigate to other files/pages within the same preview window.  They also get reloaded any time you navigate away and back to them.  You also can't access any URI that is registered within your VS Code extension.

Given all that, the preview window has a "content" `div` that dynamically changes what content it displays based on the currently selected 3D engine.  We can't explicitly execute a script that that is being referenced by a `src` attribute, and it _won't _be automatically executed when it gets dynamically inserted into the `div`, but it _will_ be executed if added to the `head`.  `link` elements (for .css files) have the same issue.  So...whenever we add new content to the `div`, we check to see if there are any `script` or `link` elements, and we add them to the `head` so that they get executed.  We'll remove them whenever the engine changes.  Now, unfortunately, there are race conditions with this, so we can't dynamically insert/remove the 3D engine javascript files the way we do for the javascript that controls the "page" for the preview.  So, those will always statically be loaded...we need to be sure that the engines are fully loaded before we dynamically insert any content that tries to reference them.

## Review notes
* All engines have now been moved to subfolders within a new `engines` folder.  So, you'll see a _ton_ of file changes for the "Cesium" engine.  There were no actual file content changes...the files were simply moved from `<root>\Cesium\` to `<root>\engines\Cesium\`.
* The content formerly in previewModel.js/css/html has been split between those files and Cesium.js/css/html since that had been the Cesium-specific preview logic before this change.

Resolves #5

### CODE REVIEW

**Comment by pjcozzi** [comment]
Super exciting, thanks @HowardWolosky!

**Comment by emackey** [comment]
I merged this into my `gltf2.0` branch, and have made an additional change there: I separated `defaultEngine` into `defaultV1Engine` and `defaultV2Engine`.  This way different glTF versions can have different default engines.

* `defaultV1Engine` -> Cesium is default, BabylonJS is removed from enum list due to incompatibility.

* `defaultV2Engine` -> BabylonJS is default, Cesium is removed from enum list (for now...).

This turned out to be an easy change to make.  I'm still planning to review a few more things, but I hope to be able to open a PR from `gltf2.0` to `master` sometime in the next few days.

**Comment by HowardWolosky** [comment]
Thanks -- I took a look at [your change](https://github.com/AnalyticalGraphicsInc/gltf-vscode/commit/0bab07fb6ac9984f059d5f13ca8907f37be97d25) and it seemed not only reasonable, but a good idea.

Any idea when you'll be pushing the glTF2.0 branch into master and publishing that to the [extensions marketplace](https://marketplace.visualstudio.com/items?itemName=cesium.gltf-vscode)?

**Comment by emackey** [comment]
@HowardWolosky Thanks!  Hopefully I will get this all merged and deployed either tonight or tomorrow night.  I realize the clock is ticking.

**Comment by emackey** [comment]
This was published moments ago.  Thanks again @HowardWolosky!

https://twitter.com/emackey/status/869729241398743040

**Pull request merged**
