### PR TITLE
Treeview update

### PR DESCRIPTION
**Pull request by najadojo**
Refactored the treeview to implement TreeDataProvider instead of a raw TextDocumentContentProvider. This provides a bit more functionality for navigation, more glTF types are present in the tree and some "pretty" icons are now present.

### CODE REVIEW

**Comment by najadojo** [comment]
@emackey thanks for the merge... will continue to work on this to supply definitionProvider and some hoverProvider stuff.

**Comment by emackey** [comment]
This is awesome.  I'm tempted to just merge what you have now.  Was thinking about a publish tonight, to get the gltf validator out there.  Do you want to include this, or hold off?

**Comment by najadojo** [comment]
Up to you... I can continue at my own pace.

**Comment by emackey** [comment]
Renamed a file in a6a9b7f07, only minor changes.  I'm bringing this into master for publishing tonight.  Please do keep going as time permits 👍

**Pull request merged**
