### PR TITLE
Watch all files referenced by glTF asset

### PR DESCRIPTION
**Pull request by bghgary**
See https://github.com/AnalyticalGraphicsInc/gltf-vscode/issues/163#issuecomment-498729502.

This works, but for textures, it seems to only update for Babylon. Not sure why, but Babylon somehow makes that the other two engines want to get the new texture also. Maybe it's some kind of caching going on, but I couldn't figure it out.

### CODE REVIEW

**Comment by najadojo** [comment]
It's been a while since I looked at the extension but can you do the watching in the editor's context (to solve the issue)? I assume the watcher is running with the preview in a separate webview.

**Comment by bghgary** [comment]
The watcher is already running in the editor context and is posting a `refresh` message to the preview panel webview when something changes.

The issue isn't about watching files. Watching files work just fine. Once the `refresh` message is sent to the webview, if the engine is running Cesium or Three.js, the engine doesn't pick up the update to the files for some reason.

**Comment by bghgary** [comment]
Specifically, it only doesn't work for textures. It works fine for glTF files. I haven't tested changing the bin files, but I suspect it works because I can see in the network tab of the dev tools that it's trying to get the bin files. The same does not happen for image files.

**Comment by bghgary** [comment]
@emackey Do you think it's okay to merge this without it working perfectly on all the engines? I don't have time to figure this out and I don't want this PR to just stay here.

**Comment by emackey** [comment]
@bghgary I'll have to carve out some time to work on this extension again.

Also I've seen a small issue (in master, in the published version), where the first change to a glTF file triggers a refresh before the "dirty" flag gets set on the document.  So, if I'm previewing a glTF and I've moved the camera somewhere interesting, my very first keystroke in the glTF document causes a preview refresh and loss of camera position, and then after that it knows from the dirty flag to stop sending refreshes with subsequent keystrokes.  I'm concerned that it's a little trigger-happy.

But that's separate from this PR.  Should this PR come out of draft mode?

**Comment by bghgary** [comment]
> But that's separate from this PR

+1

> Should this PR come out of draft mode?

If you're okay with merging it as it is without fixing all the engines, then I will make it ready.

**Comment by emackey** [comment]
I found an issue:

1. Preview a glTF model in Babylon.
2. Close the preview window.
3. Overwrite a texture file used by the model.

It posts a `refresh` to a disposed webview.  I can see code that suggests it's not supposed to be doing that, but currently this throws an unhandled exception.

**Comment by bghgary** [comment]
Good catch! Fixed.

**Pull request merged**
