### PR TITLE
glTF debugger

### LINKED ISSUE #125: Babylon preview: 'loadAsset of unknown' error
Hi folks!

I am encountering the following issue with a pretty simple model: The model is displayed nicely in the Cesium and Three previewers, however, the following error pops up using the Babylon engine:

babylon_loadasset_error

I updated to the recently released version 2.1.17 and use the 'import from GLB' with this model ([morph02.zip](https://github.com/AnalyticalGraphicsInc/gltf-vscode/files/2569829/morph02.zip)). The model itself should be fine (validator has no problems and the babylon [sandcastle](https://sandbox.babylonjs.com/) displays it nicely).

Any ideas why Babylon fails? Thank you!

### PR DESCRIPTION
**Pull request by bghgary**
I have been working on some glTF debugging capabilities. This is a work in progress.

Here are the highlights:
* Add a new `glTF` view container
* Move the `glTF Outline` tree view to the new glTF view container
* Add a new `Inspect Data` tree view to the new glTF view container
* Replace the accessor text document preview with a tree view in the `Inspect Data` view
* Add ability to inspect mesh primitive data for the `Inspect Data` view
* Add ability to enter debug mode in the preview window
  * This only works for Babylon right now and shows the new Babylon inspector
* Add ability to select (and multi-select) vertex, triangles, lines, or points when using `Inspect Data` on a mesh primitive and see them update live in the preview window when in debug mode.

TODO:
- [x] Needs some new svg icons for some of the new UI
- [x] Needs more testing especially making sure the active window tracking is working as there are a bunch of work arounds that I added due to weirdness in vscode behavior
- [ ] File bugs on vscode for the weird behavior
- [x] Make sure this PR doesn't break existing functionality
- [x] Update README
- [ ] Fix layout issue with Babylon.js Inspector
- [x] Tested on Mac

Future work:
- Support skinning/morph target
- Move Draco view into `Inspect Data`

Fixes #125

### CODE REVIEW

**Comment by emackey** [comment]
This is looking amazing so far!

**Comment by bghgary** [comment]
@emackey 
This is ready to go, except for an issue with HTML layout with the Babylon Inspector. I am almost confident is something wrong with vscode. I will work on creating a simple repro and file a bug on vscode, but I don't want this to block this PR from going in as I don't know how long that will take to fix.

Here is what the bug looks like:

**Comment by emackey** [comment]
@bghgary Thanks so much for this contribution!

My hunch on the layout issue is due to the inspector using `<div id="embed"` inside of `<div id="embed-host"` and then attempting to use `width: auto` on the parent while setting the actual width in the child.  At one point I got it "stuck" in the bad layout and was able to see in the inspector that the child was thinner than its parent.  For size-controlled web apps like this, with a UI splitter that the user can move around at the parent level, all the sizes have to flow from the parent down to the children.  Asking the browser to do even a single step in reverse up the hierarchy like that leads to circular dependencies and problems.  I've seen this happen in many Cesium apps, where a child globe window wants to fill all of its allocated child space.  In such cases, every single div in the parent ancestry needs to be commanding its childrens' sizes, otherwise the kids go crazy.

That said, I won't hold up the PR just for that.  I do want to take some time and test out a lot of these features.  Some questions off the bat:

* Are all of the features of the inspector usable?  For example there's a "Export to GLB" and "Record video" and other such buttons, are they all supposed to work?  If not, can we hide the ones that don't apply here?

* Is there a way to isolate a view of just the roughness map, just metallic, etc?  I think I saw this in one of your videos but I couldn't find the right button.

* The glTF icon in the left sidebar is super awesome, except for one tiny detail, one of my favorite pet peeves of graphical errors, it's the wrong aspect ratio.  It needs to be vertically centered in just the right amount of padding to squish it into the correct shape.  If you don't think you can get this 100% perfectly right then just tell me, because I will very likely feel compelled to redo it myself anyway.  (Note to self: further size advice here: https://github.com/Microsoft/vscode/issues/48637#issuecomment-384178403)

* If I right-click an accessor and hit "Peek Definition", I get an inset preview window but the peek no longer happens for me.  Was this intentionally removed?

* The validator sometimes calls out non-unit vectors and other per-vertex problems.  Can/should these be linked to some visual identification of the problem vertices in the display?  (Could punt this as a feature for next time).

**Comment by bghgary** [comment]
I've narrowed down the repro for the layout issue and filed a bug. https://github.com/Microsoft/vscode/issues/64647

**Comment by bghgary** [comment]
> If I right-click an accessor and hit "Peek Definition", I get an inset preview window but the peek no longer happens for me.

I've restored this functionality.

**Comment by emackey** [comment]
Thanks @bghgary!

One last question about this.  If I select a primitive and say "Inspect Data", then I get the list of verts and triangles, I can use SHIFT with the arrow keys to range-select, but I don't seem to be able to SHIFT-click to range-select, and I can't use CTRL-click for disjoint multi-selections.  In fact I don't see a way to multi-select anything other than a contiguous range.

This seems like a VSCode issue, not an issue with this PR, but I thought I would ask if you knew.

I'm going to merge this to master, but it may be a day or two before I get to publish this (my home environment is having issues, will try to get that fixed soon).

**Comment by bghgary** [comment]
> I can use SHIFT with the arrow keys to range-select, but I don't seem to be able to SHIFT-click to range-select, and I can't use CTRL-click for disjoint multi-selections. In fact I don't see a way to multi-select anything other than a contiguous range.

This is confusing for me too. I haven't found a way to multi-select with the mouse either. But there is a way to select disjoint ranges with the keyboard. Once you select a range with shift, you can move around without pressing shift, and then press shift again to add to the current selection. Should file an issue on vscode.



> a day or two before I get to publish this

There is no rush. Thanks for testing, reviewing, and merging!

**Comment by emackey** [comment]
@najadojo @HowardWolosky This is in master now, you may want to take a look too!

**Comment by emackey** [comment]
@bghgary In the previous version, clicking a node or mesh or material in the "glTF Outline" tree would take you to the correct location in the document, and highlight the corresponding JSON object.

Is that intentionally removed here?

**Comment by bghgary** [comment]
> Is that intentionally removed here?

No. I made a mistake in the window code. I'll submit a PR. Someday, I'm going to turn on some stricter flags to tsc so that this kind of error is caught at compile time.

**Pull request merged**
