### PR TITLE
Add support for Babylon preview to load current tab content

### PR DESCRIPTION
**Pull request by HowardWolosky**
Makes the Babylon previewer use the current tab content instead of the saved file content, the same way that the Cesium tab support works (although this doesn't have fallback logic to use file loading like Cesium does).

This required an update to [Babylon.js](https://github.com/BabylonJS/Babylon.js/pull/2242) to help it infer if the raw file content is actually glTF.

Resolves Issue #18

### CODE REVIEW

**Comment by emackey** [comment]
Awesome!  Will look at this soon.  Thanks so much for taking this on.

**Comment by emackey** [comment]
This change appears to somehow disable normal maps in BabylonJS.  I tried a couple of different models including BoomBox and NormalTangentTest, and two different machines.  Maybe something broke in BabylonJS?  Or maybe BabylonJS normal maps don't work with passed-in gltf contents?

**Comment by HowardWolosky** [comment]
Nice catch.  That looks like it was a regression in Babylon.  I just grabbed another updated version of the engine, and the things that _I saw_ to be broken when viewing the models looks fixed now.  It would be good to hear if you see the same.

**Comment by HowardWolosky** [comment]
With regards to direct load (file contents) vs file/uri load, the paths converge, so _that_ should not be a differentiating factor.   About to push an update that has an updated engine.

**Comment by emackey** [comment]
Version 2.0.3 published.

**Pull request merged**
